#!/bin/sh

sudo systemctl daemon-reload

for f in /config/ruvchain.*.conf
do
  if [ "$f" == "/config/ruvchain.*.conf" ];
  then
    continue
  fi

  mkdir -p /var/backups
  echo "Backing up configuration file to $f.`date +%Y%m%d`"
  cp $f $f.`date +%Y%m%d`
  echo "Normalising $f"
  /usr/local/bin/ruvchain -useconffile $f.`date +%Y%m%d` -normaliseconf > $f
done

sg users -c "/opt/vyatta/sbin/vyatta-restart-ruvchain"
